// src/styles.js
const inputBase = {
  width: "100%",
  minWidth: 0,
  display: "block",
  boxSizing: "border-box",
  height: 44,
  padding: "10px 12px",
  borderRadius: 10,
  border: "1px solid #cbd5e1",
  fontSize: 16,
  lineHeight: 1.2,
  backgroundColor: "#ffffff",
  color: "#111827",
  WebkitTextFillColor: "#111827",
  WebkitAppearance: "none",
  appearance: "none",
  boxShadow: "none",
};

const styles = {
  page: {
    minHeight: "100vh",
    background: "#f8fafc",
    padding: 12,
    fontFamily: "sans-serif",
  },
  container: {
    maxWidth: 420,
    margin: "0 auto",
  },
  header: {
    marginBottom: 12,
  },
  appTitle: {
    fontSize: 24,
    margin: "0 0 4px 0",
    color: "#111827",
  },
  tabRow: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#475569",
    fontSize: 14,
    cursor: "pointer",
  },
  tabButtonActive: {
    background: "#111827",
    color: "#ffffff",
    border: "1px solid #111827",
  },
    sectionTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#64748b",
    marginBottom: 0,
    },
  summary: {
    background: "#ffffff",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  selectedDateText: {
    fontSize: 24, // ← mainWeightと同じにする
    fontWeight: "bold",
    textAlign: "center",
    color: "#111827",
    marginTop: 4,
  },
   mainWeight: {
    fontSize: 24, // ← 34 → 24（約70%）
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 14,
    color: "#111827",
    },
  metrics: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 12,
  },
  metricRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "#f8fafc",
    borderRadius: 10,
    padding: "10px 12px",
  },
  metricName: {
    fontSize: 14,
    color: "#475569",
  },
  metricValue: {
    fontSize: 15,
    color: "#111827",
  },
  commentBox: {
    lineHeight: 1.8,
    fontSize: 14,
    color: "#334155",
    background: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    whiteSpace: "pre-line",
  },
  formCard: {
    background: "#ffffff",
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  resultCard: {
    background: "#ffffff",
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  inputRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginBottom: 12,
    alignItems: "start",
  },
  field: {
    minWidth: 0,
  },
  labelRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    height: 18,
    marginBottom: 6,
  },
  label: {
    fontSize: 13,
    color: "#475569",
    margin: 0,
  },
  hint: {
    fontSize: 12,
    color: "#a0aec0",
    whiteSpace: "nowrap",
  },
  input: inputBase,
  button: {
    width: "100%",
    padding: 14,
    borderRadius: 12,
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: 16,
    cursor: "pointer",
  },
  calendarHeader: {
    display: "grid",
    gridTemplateColumns: "40px 1fr 40px",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  calendarTitle: {
    textAlign: "center",
    fontSize: 15,
    fontWeight: 600,
    color: "#111827",
  },
  monthButton: {
    height: 36,
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    color: "#475569",
    fontSize: 14,
    cursor: "pointer",
  },
  weekdayRow: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
    marginBottom: 6,
  },
  weekdayCell: {
    textAlign: "center",
    fontSize: 12,
    color: "#94a3b8",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
    marginBottom: 16,
  },
  calendarBlankCell: {
    minHeight: 58,
  },
  calendarCell: {
    minHeight: 58,
    borderRadius: 12,
    border: "1px solid transparent",
    background: "#f8fafc",
    padding: "6px 4px",
    cursor: "pointer",
  },
  calendarCellSelected: {
    border: "1px solid #111827",
    background: "#eef2ff",
  },
  calendarDay: {
    fontSize: 12,
    color: "#475569",
    marginBottom: 6,
    textAlign: "center",
  },
  calendarWeight: {
    fontSize: 11,
    fontWeight: 600,
    color: "#111827",
    textAlign: "center",
    lineHeight: 1.2,
    minHeight: 14,
  },
  detailCard: {
    background: "#f8fafc",
    borderRadius: 12,
    padding: 12,
  },
  detailRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #e2e8f0",
  },
  detailRowLast: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0 0 0",
  },
  detailLabel: {
    fontSize: 14,
    color: "#475569",
  },
  detailValue: {
    fontSize: 15,
    color: "#111827",
  },
  historyCard: {
    background: "#ffffff",
    padding: 16,
    borderRadius: 16,
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  historyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  countBadge: {
    fontSize: 12,
    color: "#475569",
    background: "#f1f5f9",
    borderRadius: 999,
    padding: "4px 8px",
  },
  emptyHistory: {
    fontSize: 14,
    color: "#64748b",
  },
  gridList: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 8,
    marginBottom: 16,
  },
  gridCard: {
    background: "#f8fafc",
    border: "1px solid transparent",
    borderRadius: 12,
    padding: 10,
    minHeight: 82,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    textAlign: "left",
    cursor: "pointer",
  },
  gridCardSelected: {
    border: "1px solid #111827",
    background: "#eef2ff",
  },
  gridDate: {
    fontSize: 12,
    color: "#64748b",
  },
  gridWeight: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#111827",
  },
  gridDiff: {
    fontSize: 11,
    color: "#64748b",
    lineHeight: 1.4,
  },
  selectedCard: {
    marginTop: 4,
  },
  selectedHeader: {
    marginBottom: 8,
  },
  deleteMainButton: {
    width: "100%",
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    color: "#334155",
    fontSize: 14,
    cursor: "pointer",
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },

  metricHalf: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "#f8fafc",
    borderRadius: 10,
    padding: "10px 12px",
  },
   summaryHeader: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 8,
    },

   summaryColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    },
   resultMain: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    color: "#111827",
    marginBottom: 6,
    },

  resultSub: {
    display: "flex",
    justifyContent: "center",
    gap: 16,
    fontSize: 13,
    color: "#475569",
  },
  resultDate: {
    fontSize: 13,
    color: "#64748b",
    textAlign: "center",
    marginBottom: 4,
  },
};

export default styles;